campaign:
    resource: "@SuccessAdsBundle/Resources/config/routing/campaign.yml"
    prefix:   /    

campaignLog:
    resource: "@SuccessAdsBundle/Resources/config/routing/campaignLog.yml"
    prefix:   /
    
campaignTransaction:
    resource: "@SuccessAdsBundle/Resources/config/routing/campaignTransactionAccount.yml"
    prefix:   /

campaignPayment:
    resource: "@SuccessAdsBundle/Resources/config/routing/campaignPayment.yml"
    prefix:   /
