parameters:
    success.generator.order_number.class: Application\Success\PaymentsBundle\Generator\OrderNumberGenerator
    success.listener.order_number.class: Application\Success\PaymentsBundle\EventListener\OrderNumberListener

services:
    success.campaign.helper:
        class: %success_ads.helper%
        arguments: ['@success.repository.campaign', '@success.repository.campaignRealLog', '@success.repository.campaignRealStats', '@success.manager.campaignRealStats', '@success.manager.campaign', '@success.repository.campaignAccount', '%price_per_view%']

    success.campaign.twig:
        class: Success\AdsBundle\Twig\AdsExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    success.generator.order_number:
        class: "%success.generator.order_number.class%"
        arguments: ["@success.repository.order"]

    success.listener.order_number:
        class: "%success.listener.order_number.class%"
        arguments: ["@success.generator.order_number"]
        tags:
            - { name: kernel.event_listener, event: success.order.pre_create, method: generateOrderNumber, priority: 10 }
