parameters:

services:
    success.campaign.helper:
        class: %success_ads.helper%
        arguments: ['@success.repository.campaign', '@success.repository.campaignRealLog']

    success.campaign.twig:
        class: Success\AdsBundle\Twig\AdsExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }