Success\AdsBundle\Entity\Campaign:
    type: mappedSuperclass
    fields:
        name:
            type: string
            length: 128
        pricePerDay:
            type: decimal
            scale: 2
            nullable: false
        campaignType:
            type: string
            length: 16            
        active:
            type: boolean
            nullable: false
        createdDate:
            type: datetime
            column: created_date
            nullable: false
        isDeleted:
            type: boolean
            column: is_deleted
            nullable: false
        deletedDate:
            type: datetime
            column: deleted_date
            nullable: true
        unlockedDate:
            type: datetime
            column: unlocked_date
            nullable: true
        unlockedUntilDate:
            type: datetime
            column: unlocked_until_date
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: []
            nullable: false
            joinColumn:
                name: success_user_id
                referencedColumnName: id
                onDelete: SET NULL
    oneToOne:
        banner:
            targetEntity: Success\AdsBundle\Model\CampaignBannerInterface
            cascade: []
            nullable: true
            joinColumn:
                name: campaign_banner_id
                referencedColumnName: id
                onDelete: SET NULL
#        attachment:
#            targetEntity: CCDNComponent\AttachmentBundle\Entity\Attachment
#            cascade: ["persist"]
#            joinColumn:
#                name: fk_attachment_id
#                referencedColumnName: id
#                onDelete: SET NULL
