Success\AdsBundle\Entity\CampaignBanner:
    type: mappedSuperclass
    fields:
        image:
            type: string
            length: 128
            nullable: false
        link:
            type: string
            scale: 128
            nullable: true
        targetBlank:
            type: boolean
            nullable: false
            options:
                default: 1
        html:
            type: text
            nullable: true
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]