Success\AdsBundle\Entity\CampaignAccount:
    type: mappedSuperclass
    fields:
        code:
            type: string
            columnDefinition: CHAR(20) NOT NULL
        currency:
            type: string
            length: 3
            nullable: false
        total:
            type: decimal
            scale: 2
        createdDate:
            type: datetime
            column: created_date
            nullable: false
        isDeleted:
            type: boolean
            column: is_deleted
            nullable: false
        deletedDate:
            type: datetime
            column: deleted_date
            nullable: true
    manyToOne:
        user:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: []
            nullable: true
            joinColumn:
                name: success_user_id
                referencedColumnName: id
                onDelete: SET NULL
