Success\AdsBundle\Entity\CampaignLog:
    type: mappedSuperclass
    fields:
        views:
            type: integer
        clicks:
            type: integer
        createdDate:
            type: date
            column: created_date
            nullable: false
        active:
            type: boolean
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: []
            nullable: true
            joinColumn:
                name: success_user_id
                referencedColumnName: id
                onDelete: SET NULL
    manyToOne:
        campaign:
            targetEntity: Success\AdsBundle\Model\CampaignInterface
            cascade: []
            nullable: false
            joinColumn:
                name: campaign_id
                referencedColumnName: id
                onDelete: CASCADE
