Success\AdsBundle\Entity\CampaignLog:
    type: mappedSuperclass
    fields:
        views:
            type: integer
        clicks:
            type: integer
        createdDate:
            type: date
            column: created_date
            nullable: false
        active:
            type: boolean
            nullable: true
    manyToOne:
        campaign:
            targetEntity: Success\AdsBundle\Model\CampaignInterface
            cascade: []
            joinColumn:
                name: campaign_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
