Success\AdsBundle\Entity\Campaign:
    type: mappedSuperclass
    fields:
        code:
            type: string
            columnDefinition: CHAR(20) NOT NULL
        name:
            type: string
            length: 128
            nullable: false
        pricePerDay:
            type: decimal
            scale: 2
            nullable: false
        campaignType:
            type: string
            columnDefinition: ENUM('fixed', 'views') NOT NULL DEFAULT 'views'
        active:
            type: boolean
            nullable: false
            options:
                default: 1
        verified:
            type: boolean
            nullable: false
            options:
                default: 0
        views:
            type: integer
            options:
                default: 0
        createdDate:
            type: datetime
            column: created_date
            nullable: false
        isDeleted:
            type: boolean
            column: is_deleted
            nullable: true
        deletedDate:
            type: datetime
            column: deleted_date
            nullable: true
        unlockedDate:
            type: datetime
            column: unlocked_date
            nullable: false
        unlockedUntilDate:
            type: datetime
            column: unlocked_until_date
            nullable: false
    manyToOne:
        createdBy:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: []
            nullable: true
            joinColumn:
                name: success_user_id
                referencedColumnName: id
                onDelete: SET NULL
    oneToOne:
        banner:
            targetEntity: Success\AdsBundle\Model\CampaignBannerInterface
            cascade: [persist]
            nullable: true
            joinColumn:
                name: campaign_banner_id
                referencedColumnName: id
                onDelete: SET NULL
#        attachment:
#            targetEntity: CCDNComponent\AttachmentBundle\Entity\Attachment
#            cascade: ["persist"]
#            joinColumn:
#                name: fk_attachment_id
#                referencedColumnName: id
#                onDelete: SET NULL
