parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Campaign Forms.
    #
    success.form.type.campaign:
        class: %success.form.type.campaign.class%
        arguments:
            - %success.model.campaign.class%
        tags:
            - { name: form.type, alias: success_campaign }

    success.form.type.campaignBanner:
        class: %success.form.type.campaignBanner.class%
        arguments:
            - %success.model.campaignBanner.class%
        tags:
            - { name: form.type, alias: success_campaign_banner }
            
    #
    # Campaign Filters.
    #
    success.filter.type.campaign:
        class: %success.filter.campaign.class%
        arguments: []
        tags:
            - { name: form.type, alias: success_campaign_filter }
      
    success.filter.type.form.campaign:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - filter
            - success_campaign_filter
            - null
      
    success.campaign.filter:
        class: Success\AdsBundle\Filter\CoreFilter
        arguments: ['@success.filter.type.form.campaign', '@lexik_form_filter.query_builder_updater','@doctrine.orm.entity_manager', '%success.model.campaign.class%']


    #
    # CampaignLog Filters.
    #
    success.filter.type.campaignLog:
        class: %success.filter.campaignLog.class%
        arguments: []
        tags:
            - { name: form.type, alias: success_campaign_log_filter }
      
    success.filter.type.form.campaignLog:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - filter
            - success_campaign_log_filter
            - null
      
    success.campaignLog.filter:
        class: Success\AdsBundle\Filter\CoreFilter
        arguments: ['@success.filter.type.form.campaignLog', '@lexik_form_filter.query_builder_updater','@doctrine.orm.entity_manager', '%success.model.campaignLog.class%']

    #
    # CampaignTransactionAccount Filters.
    #
    success.filter.type.campaignTransactionAccount:
        class: %success.filter.campaignTransactionAccount.class%
        arguments: []
        tags:
            - { name: form.type, alias: success_campaign_transaction_account_filter }
      
    success.filter.type.form.campaignTransactionAccount:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - filter
            - success_campaign_transaction_account_filter
            - null
      
    success.campaignTransactionAccount.filter:
        class: Success\AdsBundle\Filter\CoreFilter
        arguments: ['@success.filter.type.form.campaignTransactionAccount', '@lexik_form_filter.query_builder_updater','@doctrine.orm.entity_manager', '%success.model.campaignTransactionAccount.class%']
